### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by sneccc** [mlinmg/ComfyUI-LaMA-Preprocessor#12]
While installing requirements.txt got this
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/61990796/4c0a7f2f-5ab9-4ccd-811a-e872f184e8ae)

**Comment by mlinmg** [comment]
Please make a bug report with your workflow and input image otherwise I cannot test your set up

**Comment by ntrouve-onera** [comment]
@sneccc how did you fix the first bug? (when installing the future package? i tried to install it manually, download the tar.gz, no matter what I get that cannot find src error.)

**Comment by mlinmg** [comment]
@ntrouve-onera I suggest to make a new python env for comfy, starting from scratch to see if some dependencies may have broken during the node installation. I also highly suggest to install this node via the [manager](https://github.com/ltdrdata/ComfyUI-Manager) 
Feel free to open a new issue if you still encounter problems during the installation

**Comment by ntrouve-onera** [comment]
I did install through the manager in the first place, I tried manually only as a workaround. You mean I should flush all my dependencies and let the manager redownload all? reinstall comfy alltogether? because future package is not in my env currently.

**Comment by mlinmg** [comment]
yes that would probably solve the issue. I use conda, just create a new env and install the dependencies fro comfy, after that let the manager do the work
