### ISSUE TITLE
Not Loading at start in Comfy 

### ISSUE THREAD

**Issue by gromegrom** [mlinmg/ComfyUI-LaMA-Preprocessor#19]
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\__init__.py", line 1, in <module>
    from .inpaint_Lama import (
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 44, in <module>
    from annotator.lama import LamaInpainting
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\annotator\lama\__init__.py", line 6, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'

omegaconf is installed however: 
C:\Python310\Lib\site-packages>python -m pip install omegaconf
WARNING: Ignoring invalid distribution -orch (c:\python310\lib\site-packages)
Requirement already satisfied: omegaconf in c:\users\grome\appdata\roaming\python\python310\site-packages (2.3.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\users\grome\appdata\roaming\python\python310\site-packages (from omegaconf) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\python310\lib\site-packages (from omegaconf) (6.0.1)

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Model-Manager
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\pfaeff-comfyui
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SD-Latent-Interposer
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_GradientDeepShrink
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras
   0.0 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.3 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   0.3 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy
   0.4 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.4 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   1.1 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.6 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker
   3.5 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   3.8 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

**Comment by mlinmg** [comment]
You can try to do a fresh installation of the node

**Comment by gromegrom** [comment]
By " fresh installation" you mean not doing it through the Manager?

**Comment by mlinmg** [comment]
No, I mean to delete the folder of the node and then to reinstall with the manager
Marco

Il giorno 15 dic 2023, alle ore 10:56, gromegrom ***@***.***> ha scritto:

﻿

By " fresh installation" you mean not doing it through the Manager?

**Comment by mlinmg** [comment]
There is a missing package named omegaconf, try to install it

**Comment by mlinmg** [comment]
closed for prolonged inactivity
