### ISSUE TITLE
'VAE' object has no attribute 'scale_factor'

### ISSUE THREAD

**Issue by Yorha4D** [mlinmg/ComfyUI-LaMA-Preprocessor#3]
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/116185401/74bece6e-1209-4cb2-b1da-fddf7b244ce9)
@mlinmg When I load workflow_ After lama.json runs and generates an error

**Comment by mlinmg** [comment]
Thank you for pointing it out, i had to modify some default nodes in the beginning, now this is patched
