### ISSUE TITLE
could not broadcast input array from shape (590,502) into shape (584,496)

### ISSUE THREAD

**Issue by hben35096** [mlinmg/ComfyUI-LaMA-Preprocessor#5]
**Describe the bug**
Error occurred when executing lamaPreprocessor:

could not broadcast input array from shape (590,502) into shape (584,496)

File "/mnt/workspace/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/mnt/workspace/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/mnt/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/inpaint_Lama.py", line 405, in preprocess
final_img_with_alpha[:, :, 3] = np.where(mask_alpha.squeeze(), 255, 0)

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/139383150/ab1c205e-6e85-4693-968b-93375180cda3)
**Additional context**

**Comment by hben35096** [comment]
I tested a few more images, it should be the problem with the image in the image above, it can expand left and right, but expanding up and down will error.
Everything works fine with the other pictures. Thank you for making such a good node!

**Comment by amimi818** [comment]
I had the same problem

**Comment by hben35096** [comment]
version：2e10d9aec35ae8bb77f08d89bd31195476233a86
I found that expansion is ineffective when there is a mask;
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/139383150/ff9bd17c-9f51-4d00-a8a2-4c36e0705301)

When there is no mask, a certain value is 0, which will report an error;
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/139383150/d0f87a8a-7138-49bd-b38b-61319869c8b5)

When there is no mask, neither value is 0, expansion is normal;
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/139383150/841e5e08-e423-4060-86c9-e883405057d4)

**Comment by mlinmg** [comment]
Yes this is because you should not give a mask and an expansion value. If you give an expansion value it will generate the mask on itself(like with the pad for outpaint node)

**Comment by mlinmg** [comment]
Closing since it has been inactive for a while
