### ISSUE TITLE
无法安装加载插件，如下报错

### ISSUE THREAD

**Issue by Linaghan34** [mlinmg/ComfyUI-LaMA-Preprocessor#8]
![image](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/127322778/c85b3a9c-c87d-4e43-bfd4-49eea167309b)

尝试修改对ldm.py的print语法，全部加了(),仍然报错

**Comment by mlinmg** [comment]
Sorry I can't understand, I will appreciate you translating this bug in English

**Comment by mlinmg** [comment]
Closing since it has been inactive for a while
